## HW6
#### question3
```sql
CREATE TABLE user(
    id INT,
    user_name string,
    sex string,
    age int,
    phone string
);

INSERT INTO user(id, user_name, sex, age, phone)
VALUES(101, 'xiaoming', 'male', 17, '18178674563');
INSERT INTO user(id, user_name, sex, age, phone)
VALUES(102, 'xiaohong', 'female', 20, '19678634261');
```

#### question4
```sql
SELECT * FROM user WHERE age >= 20 AND age <= 30;
```

#### question5
```sql
DELETE FROM user WHERE user_name LIKE '%张%';
```

#### question6
```sql
SELECT AVG(age) AS AverageAge FROM user;
```

#### question7
```sql
SELECT * FROM user 
WHERE age >= 20 AND age <= 30 AND user_name LIKE '%张%' 
ORDER BY age DESC;
```

#### question8
```sql
CREATE TABLE team(
    id INT PRIMARY KEY,
    teamName VARCHAR(225)
);

CREATE TABLE score(
    id INT PRIMARY KEY,
    teamid INT,
    userid INT,
    score INT,
    FOREIGN KEY (teamid) REFERENCES team(id),
    FOREIGN KEY (userid) REFERENCES user(id)
)
```

#### question9
```sql
SELECT u.* FROM user u 
JOIN score s ON u.id = s.userid
JOIN team t ON s.teamid = t.id 
WHERE t.teamName = 'ECNU' AND u.age < 20;
```

#### question10
```sql
SELECT SUM(s.score) AS TotalScore 
FROM team t 
JOIN score s ON t.id = s.teamid 
WHERE t.teamName = 'ECNU';
```